name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 52.79.149.244
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo cp ~/orrne-server/index.html /var/www/html/index.html
          sudo systemctl restart nginx

